services:
  - type: static_site
    name: AlertMe
    env: static
    branch: main
    rootDir: web
    buildCommand: npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://alertme-api-mxkp.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web_service
    name: AlertMe API
    env: docker
    branch: main
    rootDir: backend/alertme
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_OAUTH2_SUCCESS_REDIRECT_URL
        value: https://alertme-hirn.onrender.com/login
